### ISSUE TITLE
First installation sometimes result in an exception.

### ISSUE THREAD

**Issue by crynobone** [orchestral/installer#1]
```
[2015-06-14 17:15:26] local.ERROR: exception 'InvalidArgumentException' with message 'Unable to verify unknown action .' in /vagrant/vendor/orchestra/auth/src/Authorization/AuthorizationTrait.php:51
Stack trace:
#0 /vagrant/vendor/orchestra/auth/src/Authorization/Authorization.php(119): Orchestra\Authorization\Authorization->checkAuthorization(Array, 'manage-users')
#1 /vagrant/vendor/orchestra/foundation/src/Http/Handlers/UserMenuHandler.php(42): Orchestra\Authorization\Authorization->can('manage-users')
#2 [internal function]: Orchestra\Foundation\Http\Handlers\UserMenuHandler->authorize(Object(Orchestra\Authorization\Authorization))
#3 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#4 /vagrant/vendor/orchestra/foundation/src/Support/MenuHandler.php(168): Illuminate\Container\Container->call(Array)
#5 /vagrant/vendor/orchestra/foundation/src/Support/MenuHandler.php(54): Orchestra\Foundation\Support\MenuHandler->passesAuthorization()
#6 [internal function]: Orchestra\Foundation\Support\MenuHandler->handle()
#7 /vagrant/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(345): call_user_func_array(Array, Array)
#8 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#9 /vagrant/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(220): call_user_func_array(Object(Closure), Array)
#10 /vagrant/vendor/orchestra/foundation/src/Http/Middleware/UseBackendTheme.php(51): Illuminate\Events\Dispatcher->fire('orchestra.start...')
#11 /vagrant/vendor/orchestra/foundation/src/Http/Middleware/UseBackendTheme.php(35): Orchestra\Foundation\Http\Middleware\UseBackendTheme->beforeSendingThroughPipeline()
#12 [internal function]: Orchestra\Foundation\Http\Middleware\UseBackendTheme->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /vagrant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /vagrant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 /vagrant/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(229): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#21 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /vagrant/vendor/orchestra/messages/src/Http/Middleware/StoreMessageBag.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Orchestra\Messages\Http\Middleware\StoreMessageBag->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#25 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#28 /vagrant/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#31 /vagrant/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#34 /vagrant/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#37 /vagrant/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#40 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /vagrant/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(86): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 /vagrant/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
```

**Comment by crynobone** [comment]
Should be fixed.
